name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy server code
    runs-on: [self-hosted, linux, X64, parrot-echo]
    steps:
      - uses: actions/checkout@master
      - name: Copy files from server folder
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SERVER_KEY }}
          source: "server/*"
          target: "dev/"
      - name: Run code with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ./dev/server
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm install 8 && nvm use 8
            npm i -g pm2
            npm ci
            pm2 start ecosystem.config.js --only dev
            pm2 save
            
